# Railway Configuration for OpenAI Middleware
# Uses Dockerfile for reliable, controlled builds

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.middleware"

[deploy]
# Start command is defined in Dockerfile.middleware CMD
# Do NOT override here - let Dockerfile handle it for proper variable expansion
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

# Resource limits (Railway free tier: 512MB RAM, 0.5 vCPU)
# Can be adjusted in Railway dashboard if needed
