# Railway Configuration for OpenAI Middleware
# This file tells Railway how to build and deploy the middleware service

[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
# Start the FastAPI middleware on Railway's dynamic PORT
startCommand = "uvicorn src.openai_middleware:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

# Resource limits (Railway free tier: 512MB RAM, 0.5 vCPU)
# These are defaults, can be adjusted in Railway dashboard
