# Railway Configuration for OpenAI Middleware
# Uses Dockerfile for reliable, controlled builds

[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.middleware"

[deploy]
# Start command (defined in Dockerfile, but can override here if needed)
startCommand = "uvicorn src.openai_middleware:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "always"

# Resource limits (Railway free tier: 512MB RAM, 0.5 vCPU)
# Can be adjusted in Railway dashboard if needed
